In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
folder="/content/drive/MyDrive/資料科學自學聖經/ch03A/"

##使用 requests讀取網頁原始碼

In [ ]:
import requests
url = 'http://www.e-happy.com.tw/'
html = requests.get(url)
html.encoding="utf-8"
print(html.text)

# CSV檔案的讀取

In [4]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/資料科學自學聖經/ch03A/covid19_20231109.csv')
df

        country_ch                country_en        cases     deaths
0               美國             United States  102,717,337  1,143,992
1               印度                     India   44,689,072    530,776
2               法國                    France   39,661,650    165,135
3               德國                   Germany   38,241,231    168,808
4               巴西                    Brazil   37,085,520    699,310
..             ...                       ...          ...        ...
197            吐瓦魯                    Tuvalu        2,779          0
198             紐埃                      Niue          747          0
199  國際運輸工具(鑽石公主號)  Int'l conveyance (Japan)          741         13
200             教廷                  Holy See           29          0
201             北韓               North Korea            2          1

[202 rows x 4 columns]

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_2['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

# JSON資料的讀取

In [6]:
import pandas as pd
#import json

#with open('/content/drive/MyDrive/資料科學自學聖經/ch03A/covid19.json') as f:

#print(f)
data = json.load(f)

df = pd.json_normalize(data)
df = pd.read_json('/content/drive/MyDrive/資料科學自學聖經/ch03A/covid19.json')
df

NameError: ignored

# Excel試算表檔案的讀取

In [7]:
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/資料科學自學聖經/ch03A/covid19.xlsx')
df

    country_ch        country_en     cases  deaths
0           美國     United States  76407539  923087
1           印度             India  42272014  502874
2           巴西            Brazil  26599593  632621
3           法國            France  20804372  132923
4           英國    United Kingdom  17866632  158363
..         ...               ...       ...     ...
193         東加             Tonga         8       0
194        萬那杜           Vanuatu         7       1
195      馬紹爾群島  Marshall Islands         7       0
196   密克羅尼西亞聯邦        Micronesia         1       0
197       庫克群島      Cook Islands         1       0

[198 rows x 4 columns]

# HTML網頁資料讀取

In [23]:
import pandas as pd

url = 'https://www.tiobe.com/tiobe-index/'
tables = pd.read_html(url, keep_default_na=False)
tables[0].head(30)

,Oct 2023,Oct 2022,Change,Programming Language,Programming Language.1,Ratings,Change.1
0,1,1,,,Python,14.82%,-2.25%
1,2,2,,,C,12.08%,-3.13%
2,3,4,,,C++,10.67%,+0.74%
3,4,3,,,Java,8.92%,-3.92%
4,5,5,,,C#,7.71%,+3.29%
5,6,7,,,JavaScript,2.91%,+0.17%
6,7,6,,,Visual Basic,2.13%,-1.82%
7,8,9,,,PHP,1.90%,-0.14%
8,9,10,,,SQL,1.78%,+0.00%
9,10,8,,,Assembly language,1.64%,-0.75%
10,11,11,,,Go,1.37%,+0.10%
11,12,23,,,Scratch,1.37%,+0.69%
12,13,18,,,Delphi/Object Pascal,1.30%,+0.46%
13,14,14,,,MATLAB,1.27%,+0.09%
14,15,15,,,Swift,1.07%,+0.02%
15,16,19,,,Fortran,1.02%,+0.23%
16,17,12,,,R,0.96%,-0.26%
17,18,28,,,Kotlin,0.96%,+0.53%
18,19,16,,,Ruby,0.92%,+0.05%
19,20,20,,,Rust,0.91%,+0.22%

In [ ]:
import pandas as pd

url = 'https://www.tiobe.com/tiobe-index/'

df = pd.DataFrame(pd.read_html(url, keep_default_na=False))
df.to_csv('/content/drive/MyDrive/資料科學自學聖經/ch03A/tiobe.csv')
df.head(20)

# 儲存資料為檔案

In [11]:
import pandas as pd

scores = {'國文':{'王小明':65,'李小美':90,'陳大同':81,'林小玉':79},
          '英文':{'王小明':92,'李小美':72,'陳大同':85,'林小玉':53},
          '數學':{'王小明':78,'李小美':76,'陳大同':91,'林小玉':47},
          '自然':{'王小明':83,'李小美':93,'陳大同':89,'林小玉':94},
          '社會':{'王小明':70,'李小美':56,'陳大同':94,'林小玉':80}}
df = pd.DataFrame(scores)
df.to_csv('/content/drive/MyDrive/資料科學自學聖經/ch03A/scores.csv')

#擷取Youtube的畫面

In [22]:
import requests
url = 'https://img.youtube.com/vi/qo3H-VgXmHE/sddefault.jpg'
r = requests.get(url)

with open('/content/drive/MyDrive/資料科學自學聖經/ch03A/ng.jpg', 'wb') as f:
    f.write(r.content)

# requests模組：讀取網站檔案

In [ ]:
import requests
url = 'http://www.ehappy.tw/demo.htm'
r = requests.get(url)
print(r.text)

<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello</title>
  </head>
  <body>
    <p>Hello World!</p>
  </body>
</html>

In [ ]:
import requests
url = 'http://ehappy.tw/bsdemo1.htm'
html = requests.get(url)
html.encoding="utf-8"
print(html.text)

<!doctype html>
<html lang="zh">
  <head>
    <meta charset="UTF-8">
    <title>我是網頁標題</title>
  </head>
  <body>
    <h1 class="large">我是標題</h1>
    <div>
      <p>我是段落</p>
      <img src="https://www.w3.org/html/logo/downloads/HTML5_Logo_256.png" alt="我是圖片">
      <a href="http://www.e-happy.com.tw">我是超連結</a>
    </div>
  </body>
</html>

In [ ]:
import requests
# 將查詢參數定義為字典資料加入GET請求中
payload = {'key1': 'value1', 'key2': 'value2'}
r = requests.get("http://httpbin.org/get", params=payload)
print(r.text)

{
  "args": {
    "key1": "value1",
    "key2": "value2"
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.31.0",
    "X-Amzn-Trace-Id": "Root=1-654a2b33-18b756757bdcbea95099a95f"
  },
  "origin": "34.125.245.168",
  "url": "http://httpbin.org/get?key1=value1&key2=value2"
}

In [ ]:
import requests
# 將查詢參數加入POST請求中
payload = {'key1': 'value1', 'key2': 'value2'}
r = requests.post("http://httpbin.org/post", data=payload)
print(r.text)

{
  "args": {},
  "data": "",
  "files": {},
  "form": {
    "key1": "value1",
    "key2": "value2"
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Content-Length": "23",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org",
    "User-Agent": "python-requests/2.31.0",
    "X-Amzn-Trace-Id": "Root=1-654a2b39-78aaecb67415286047d823f7"
  },
  "json": null,
  "origin": "34.125.245.168",
  "url": "http://httpbin.org/post"
}

In [ ]:
import requests
url = 'https://img.youtube.com/vi/qo3H-VgXmHE/sddefault.jpg'
r = requests.get(url)

with open('/content/drive/MyDrive/資料科學自學聖經/ch03A/ng.jpg', 'wb') as f:
    f.write(r.content)

# BeautifulSoup模組：網頁解析

In [29]:
import requests
from bs4 import BeautifulSoup
url = 'http://www.e-happy.com.tw/'
html = requests.get(url)
html.encoding = 'UTF-8'
sp = BeautifulSoup(html.text, 'html.parser')
print(sp.title)
print(sp.title.text)
print(sp.h1)

<title>eHappy 文淵閣工作室 : 快樂分享、快樂學習</title>
eHappy 文淵閣工作室 : 快樂分享、快樂學習
<h1 class="h1function"> </h1>

In [26]:
from bs4 import BeautifulSoup
html = '''
<html>
  <head><meta charset="UTF-8"><title>我是網頁標題</title></head>
  <body>
      <p id="p1">我是段落一</p>
      <p id="p2" class='red'>我是段落二</p>
  </body>
</html>
'''
sp = BeautifulSoup(html, 'html.parser')
print(sp.find('p'))
print(sp.find_all('p'))
print(sp.find('p', {'id':'p2', 'class':'red'}))
print(sp.find('p', id='p2', class_= 'red'))

<p id="p1">我是段落一</p>
[<p id="p1">我是段落一</p>, <p class="red" id="p2">我是段落二</p>]
<p class="red" id="p2">我是段落二</p>
<p class="red" id="p2">我是段落二</p>

[練習]擷取線上網站的網頁架構相關資訊 以http://www.e-happy.com.tw/為範例

In [ ]:
import requests
from bs4 import BeautifulSoup
url = 'http://www.e-happy.com.tw/'
html = requests.get(url)
html.encoding = 'UTF-8'
sp  = BeautifulSoup(html.text, 'html.parser')
sp1 = BeautifulSoup(html, 'html.parser')

print(sp.title)
print(sp.title.text)
print(sp.h1)

print(sp1.find('p'))
print(sp1.find_all('p'))
print(sp1.find('p', {'id':'p2', 'class':'red'}))
print(sp1.find('p', id='p2', class_= 'red'))

In [27]:
from bs4 import BeautifulSoup
html = '''
<html>
  <head><meta charset="UTF-8"><title>我是網頁標題</title></head>
  <body>
      <p id="p1">我是段落一</p>
      <p id="p2" class='red'>我是段落二</p>
  </body>
</html>
'''
sp = BeautifulSoup(html, 'html.parser')
print(sp.select('title'))
print(sp.select('p'))
print(sp.select('#p1'))
print(sp.select('.red'))

[<title>我是網頁標題</title>]
[<p id="p1">我是段落一</p>, <p class="red" id="p2">我是段落二</p>]
[<p id="p1">我是段落一</p>]
[<p class="red" id="p2">我是段落二</p>]

In [28]:
html = '''
<html>
  <head><meta charset="UTF-8"><title>我是網頁標題</title></head>
  <body>
      <img src="http://www.ehappy.tw/python.png">
      <a href="http://www.e-happy.com.tw">超連結</a>
  </body>
</html>
'''
sp = BeautifulSoup(html, 'html.parser')
# 用 回傳值.get(屬性名稱) 取得圖片及超連結的網址
print(sp.find('img').get('src'))
print(sp.find('a').get('href'))
# 用 回傳值[屬性名稱] 取得圖片及超連結的網址
print(sp.find('img')['src'])
print(sp.find('a')['href'])

http://www.ehappy.tw/python.png
http://www.e-happy.com.tw
http://www.ehappy.tw/python.png
http://www.e-happy.com.tw

[Lab3-1]PTT 美食版爬蟲

In [ ]:
import requests
from bs4 import BeautifulSoup
#url= 'https://www.ptt.cc/bbs/Food/index.html'
url = 'http://www.e-happy.com.tw/'
html = requests.get(url)
html.encoding="utf-8"
sp = BeautifulSoup(html.text,'html.parser')
print(sp)

In [39]:
import requests
from bs4 import BeautifulSoup
url= 'https://www.ptt.cc/bbs/Food/index.html'
html = requests.get(url)
html.encoding="utf-8"
sp = BeautifulSoup(html.text,'html.parser')
links = sp.find_all("div", class_="title")
for link in links:
    adata = link.find("a")
    print("http://www.ptt.cc" + adata['href'], adata.text)

http://www.ptt.cc/bbs/Food/M.1699505415.A.431.html [食記] 夏威夷 Ray's Kiawe Broiled Chicken烤雞
http://www.ptt.cc/bbs/Food/M.1699508251.A.41A.html [食記] 桃園內壢牛排館 牛B牛排工場
http://www.ptt.cc/bbs/Food/M.1699509622.A.159.html [食記] 台中 北屯 鹿寮享自在
http://www.ptt.cc/bbs/Food/M.1355673582.A.5F7.html [公告] Food板 板規 V3.91
http://www.ptt.cc/bbs/Food/M.1190944426.A.E6C.html [公告] 發文請在標題加上地區及提供地址電話。^^
http://www.ptt.cc/bbs/Food/M.1128132666.A.0FD.html [公告] 文章被刪除者請洽精華區的資源回收桶
http://www.ptt.cc/bbs/Food/M.1496532469.A.C36.html [公告] 新增板規22：發文禁附延伸閱讀連結

In [ ]:
import requests, os
from bs4 import BeautifulSoup
url = 'https://srm.com.tw/%e9%9b%bb%e5%bd%b1%e7%b0%a1%e4%bb%8b/%e7%86%b1%e6%98%a0%e4%b8%ad/'
r = requests.get(url)
sp = BeautifulSoup(r.text, 'html.parser')
datas = sp.find_all('article', class_='main_color inner-entry')
for i in range(len(datas)):
    print(f"【{datas[i].find('header').a['title']}】")
    print(datas[i].find('div', itemprop='text').text)
    print(datas[i].find('header').a['href'])
    print(datas[i].img['src'])
    if not os.path.exists('photos'):
        os.mkdir('photos')
    with open('photos/'+datas[i].find('header').a['title']+'.jpg', 'wb') as f:
        f.write(requests.get(datas[i].img['src']).content)
    print()

In [45]:
import requests
from bs4 import BeautifulSoup
url = "https://covid19dashboard.cdc.gov.tw/dash5"
html = requests.get(url)

# 將文字資料轉為字典格式
datas = eval(html.text)
# 取出每個欄位及值
for k, v in datas["0"].items():
    print(k +":"+ str(v))

發病日:2020\/1\/1
本土感染:0.0
境外移入:0.0
敦睦艦隊:0.0

# 文字及檔案資料的收集

In [46]:
content='''Hello Python
中文字測試
Welcome'''
f=open('file1.txt', 'w', encoding='utf-8', newline="")
f.write(content)
f.close()

In [48]:
content='''Hello Python
中文字測試
Welcome'''
with open('file2.txt', 'w', encoding='utf-8', newline="") as f:
    f.write(content)

In [50]:
with open('file2.txt', 'r', encoding='utf-8') as f:
    output_str=f.read()
    print(output_str)   # Hello

Hello Python
中文字測試
Welcome

In [51]:
with open('file1.txt', 'r', encoding ='UTF-8') as f:
    print(f.readline())
    print(f.readline(3))

Hello Python

中文字

In [52]:
with open('file1.txt', 'r', encoding='utf-8') as f:
    content=f.readlines()
    print(type(content))
    print(content)

<class 'list'>
['Hello Python\n', '中文字測試\n', 'Welcome']

In [53]:
with open('file1.txt', 'r', encoding='utf-8') as f:
    print(f.readlines())

['Hello Python\n', '中文字測試\n', 'Welcome']

In [54]:
import requests

imgurl = 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
r = requests.get(imgurl)

with open('google.png', 'wb') as f:
  f.write(r.content)